//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.10 at 08:50:18 PM CET 
//


package es.ujaen.sinai.nlptoolsshare;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sentence_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sentence_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute ref="{http://sinai.ujaen.es/nlptoolsshare}beginspan use="required""/>
 *       &lt;attribute ref="{http://sinai.ujaen.es/nlptoolsshare}endspan use="required""/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sentence_type")
public class SentenceType {

    @XmlAttribute(name = "beginspan", namespace = "http://sinai.ujaen.es/nlptoolsshare", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger beginspan;
    @XmlAttribute(name = "endspan", namespace = "http://sinai.ujaen.es/nlptoolsshare", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger endspan;

    /**
     * Gets the value of the beginspan property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBeginspan() {
        return beginspan;
    }

    /**
     * Sets the value of the beginspan property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBeginspan(BigInteger value) {
        this.beginspan = value;
    }

    /**
     * Gets the value of the endspan property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEndspan() {
        return endspan;
    }

    /**
     * Sets the value of the endspan property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEndspan(BigInteger value) {
        this.endspan = value;
    }

}
