(function () {
    if (typeof window.Localization == 'undefined') window.Localization = { };
    window.Localization.resourcesBG = undefined;
    window.Localization.resourcesEN = undefined;
    window.Localization.resourcesES = {
		Browse_Dots: 'Examinar...',
		BrowserNotSupported_Body: 'Por favor, actualiza tu navegador',
		BrowserNotSupported_Title: 'El navegador que estás utilizando no está soportado actualmente',
		Create_Account_C: 'CREAR CUENTA',
		CreateUserAccount_SuccessMessage: 'Tu cuenta ha sido creada con éxito. Se te ha enviado un correo con instrucciones detalladas para activar tu cuenta.',
		CreateUserAccount_SuccessNote: 'NOTA: Si dentro de una hora no has recibido el mensaje, por favor revisa la carpeta de correo no deseado (Spam). Si el mensaje no ha llegado, por favor regístrate de nuevo en Open Book.',
		DocumentEdit_AskCarerHint: 'Selecciona la parte problemática del texto y haz click en el botón. Escribe tu pregunta en el cuadro de texto de abajo',
		DocumentEdit_Bold: 'En negrita',
		DocumentEdit_BoldHint: 'Selecciona un fragmento del texto y luego haz click aquí para poner en negrita el fragmento de texto seleccionado',
		DocumentEdit_Close: 'CERRAR',
		DocumentEdit_Convert_Text_C: 'PERSONALIZAR',
		DocumentEdit_DocName: 'Nombre del documento:',
		DocumentEdit_ExplainWithPictureHint: 'Selecciona una palabra del texto y haz click en el botón. Verás la imagen en el cuadro de texto de abajo',
		DocumentEdit_ExplainWordHint: 'Selecciona una palabra del texto y haz click en el botón. Verás la definición en el cuadro de texto de abajo',
		DocumentEdit_Highlight: 'Aumentar',
		DocumentEdit_HighlightHint: 'Selecciona un fragmento del texto y haz click en el botón',
		DocumentEdit_Magnify: 'Aumentar',
		DocumentEdit_MagnifyOffHint: 'Haz click en el botón para ver el documento en modo aumentado',
		DocumentEdit_MagnifyOnHint: 'Estás en modo aumentado. Utiliza el ratón o las flechas para aumentar el tamaño de las frases del texto. Haz click en el botón para desactivar esta opción.',
		DocumentEdit_NewLabel_Placeholder: 'Escribe el nombre de la etiqueta aquí',
		DocumentEdit_Notes: 'Notas',
		DocumentEdit_NotesHint: 'Haz click en el botón e inserta tu nota en el texto',
		DocumentEdit_NotesOnHint: 'Inserta  tu nota en el texto. Escribe tu nota en el cuadro de texto de abajo.',
		DocumentEdit_Save_Result_C: 'GUARDAR',
		DocumentEdit_SelectText: 'Seleccionar texto',
		DocumentEdit_SizeHint: 'Haz click en el botón y selecciona un tamaño de fuente para el documento.',
		DocumentEdit_TextInput_Placeholder: 'Escribe o copia y pega el texto aquí.',
		DocumentEdit_Theme: 'Tema',
		DocumentEdit_ThemeHint: 'Haz click en el botón y selecciona un tema para el documento.',
		DocumentEdit_Underline: 'Subrayar',
		DocumentEdit_UnderlineHint: 'Selecciona un fragmento del texto y haz click aquí para insertar una línea debajo del fragmento de texto seleccionado',
		DocumentEdit_UrlInput_Placeholder: 'Escribe o copia y pega la dirección web aquí.',
		DocumentReview_Accept: 'Aceptar',
		DocumentReview_AddDefinition: 'Incluir definición',
		DocumentReview_AddImage: 'Insertar Imagen',
		DocumentReview_AltStructures: 'estructura alternativa',
		DocumentReview_Anaphoras: 'Anáforas',
		DocumentReview_ConfirmReprocess: 'Todas las imágenes y el formato se perderán para la oración actual . ¿Quieres continuar?',
		DocumentReview_ContactUser: 'Contactar Usuario',
		DocumentReview_Custom: 'Personalizado',
		DocumentReview_Delete: 'borrar:',
		DocumentReview_Explain: 'Explicar',
		DocumentReview_Hide: 'ocultar',
		DocumentReview_Images: 'Imágenes:',
		DocumentReview_InsertAnaphora: 'quiere decir…',
		DocumentReview_InsertDefinition: 'Insertar definición',
		DocumentReview_InsertImage: 'Insertar imagen',
		DocumentReview_NoteText: 'Añadir nota:',
		DocumentReview_ObstaclesPlural: 'obstáculo detectado',
		DocumentReview_ObstaclesSingular: 'obstáculo eliminado',
		DocumentReview_Original: 'original:',
		DocumentReview_OriginalSentence: 'Frase original:',
		DocumentReview_Replace: 'Reemplazar',
		DocumentReview_ReplaceWithSynonym: 'Reemplazar por un sinónimo',
		DocumentReview_Reprocess: 'Reprocesar',
		DocumentReview_ReprocessDialogTitle: 'Confirmar reprocesar',
		DocumentReview_Retry: 'Reintentar',
		DocumentReview_SaveChanges: 'Los cambios realizados no se guardarán si abandonas la página ahora.',
		DocumentReview_SelectStructure: 'Selectiona estructura',
		DocumentReview_Show: 'mostrar',
		DocumentReview_Split: 'dividir:',
		DocumentReview_Summary: 'Resumen',
		DocumentReview_Synonyms: 'Sinónimo',
		DocumentReview_TransformedSentence: 'Frase adaptada:',
		Documents_Add_C: 'AÑADIR',
		Documents_Delete_C: 'ELIMINAR',
		Documents_Edit_C: 'EDITAR',
		Documents_New_Document_C: 'NUEVO DOCUMENTO',
		Documents_NoDocument_Selected: '¡ No has seleccionado ningún documento!',
		Documents_Print_C: 'IMPRIMIR',
		Documents_Title: 'Documentos de {0}',
		DocumentsLibrary_ApplyLabel: 'Aplicar etiqueta',
		DocumentsLibrary_ClearText: 'Borrar texto',
		DocumentsLibrary_CreateLabel: 'Crear etiqueta',
		DocumentsLibrary_Dialog_Label_Name: 'Inserta el nombre de la etiqueta:',
		DocumentsLibrary_Dialog_NoName: '¡No se puede crear una etiqueta sin nombre!',
		DocumentsLibrary_Dialog_Pick_Color: 'Escoge el color de la etiqueta:',
		DocumentsLibrary_Dialog_Pick_Label_FontColor: 'Escoge el color de la fuente de la etiqueta:',
		DocumentsLibrary_Labels: 'Etiquetas',
		DocumentsLibrary_ManageLabels: 'Gestión de etiquetas',
		DocumentsLibrary_Pages: 'Páginas:',
		DocumentsLibrary_RemoveLabels: 'Eliminar etiqueta',
		DocumentsLibrary_Search: 'Buscar:',
		Download: 'Descargar',
		EditDociment_NotificationRelatedDocument: 'Relativo al documento:',
		EditDocument_AddNote: 'Añadir nota',
		EditDocument_AskCarer: 'Preguntar a tu intermediario',
		EditDocument_AskCarerMessage: 'El texto ha sido enviado a tu intermediario.  Puedes escribir aquí tu mensaje',
		EditDocument_AskCarerSent: 'Tu solicitud ha sido enviada correctamente.',
		EditDocument_ContentSaved: 'Contenido guardado',
		EditDocument_Conv_Text: 'Texto personalizado',
		EditDocument_Done: 'Acabado',
		EditDocument_ExplainWithPicture: 'Explicar con una imagen',
		EditDocument_ExplainWord: 'Explicar palabra',
		EditDocument_File: 'Fichero',
		EditDocument_HereExplanation: 'Aquí está la definición del término seleccionado',
		EditDocument_NewNoteText: 'Esta es tu nueva nota',
		EditDocument_NoDefinition: 'No se encontró ninguna definición',
		EditDocument_NoFile: 'Por favor, selecciona un fichero',
		EditDocument_NoteSaved: 'Tu nota ha sido guardada correctamente',
		EditDocument_NoText: 'Por favor, inserta el texto',
		EditDocument_NoTextSelected: 'Por favor, selecciona el texto a resaltar',
		EditDocument_NotificationFrom: 'De:',
		EditDocument_NotSaved: 'Los cambios realizados no se guardarán si abandonas la página ahora.',
		EditDocument_NoUrl: 'Por favor, inserta la URL',
		EditDocument_Orig_Text: 'Texto original',
		EditDocument_Pictures: 'Imágenes:',
		EditDocument_PrivateDocument: 'Documento privado',
		EditDocument_SampleThemeText: 'Ejemplo de tema para el texto',
		EditDocument_Save_Document: 'Guardar documento como',
		EditDocument_SelectAWord: 'Selecciona un término',
		EditDocument_SelectPatient: 'Selecciona un usuario:',
		EditDocument_SelectPatientError: 'Tienes que seleccionar un usuario',
		EditDocument_SelectProblematic: 'Selecciona el fragmento del texto que sea problemático',
		EditDocument_Send: 'Enviar',
		EditDocument_ShareWithCarer: 'Compartir con tu intermediario',
		EditDocument_ShowMultiwords: 'Mostrar expresiones',
		EditDocument_ShowObstacles: 'Mostrar obstáculos',
		EditDocument_Size: 'Tamaño',
		EditDocument_Take_The_Test: 'Haz el test',
		EditDocument_Text: 'Texto',
		EditDocument_URL_C: 'URL',
		EditPatientDetails_Additional_Information: 'Información adicional:',
		EditPatientDetails_Age: 'Edad:',
		EditPatientDetails_Age_Invalid: 'La edad proporcionada debe estar comprendida entre 1 y 100',
		EditPatientDetails_Edit_Patient: 'Editar usuario',
		EditPatientDetails_Gender: 'Sexo:',
		EditPatientDetails_Not_Same_Password: 'La contraseña no coincide con el campo de confirmación de contraseña.',
		EditPatientDetails_TabAccount: 'Información sobre el perfil',
		EditPatientDetails_TabPreferences: 'Preferencias',
		EditPatientDetails_Update_Account_C: 'ACTUALIZAR CUENTA',
		Email: 'Correo electrónico (email):',
		Email_Req: '¡El campo “Correo electrónico (email)” es obligatorio!',
		Error_ButtonBack: 'Volver',
		Error_GeneralError: 'Ha ocurrido un error inesperado! Por favor vuelve a la página anterior y prueba de nuevo.',
		Error_List: 'Listado de errores:',
		ExplainWord: 'Explicar palabra',
		ExplainWord_NoPictures: 'No existen definiciones para el término dado',
		Explanations_ContinueToTheText: 'Continuar al texto',
		Feedback_ErrorEmpty: '¡No puedes enviar un mensaje vacio!',
		Feedback_RecepientError: 'El mensaje no pudo ser entregado a su destinatario. Por favor, inténtalo más tarde.',
		Feedback_SendFeedback: 'Enviar opinión sobre el sistema',
		Feedback_SendSentFeedback: 'Enviar opinión sobre la oración',
		Feedback_SMTPError: 'Ha ocurrido un error SMTP durante el envío del mensaje. Por favor, inténtalo más tarde.',
		Feedback_Success: 'Tu opinión se ha enviado con éxito. ¡Gracias!',
		FileUpload_FileNotCorrectType: '¡El fichero seleccionado para cargar no está en el formato correcto!',
		FileUpload_FileTooBig: 'El fichero seleccionado es demasiado grande. Selecciona un fichero menor que {0}.',
		First_Name: 'Nombre:',
		First_Name_Req: '¡El campo “Nombre” es obligatorio!',
		GenderEnum_Female: 'Feminino',
		GenderEnum_Male: 'Masculino',
		Help_NotAvailable: 'La ayuda no está disponible en este momento',
		Highlight: 'Aumentar',
		Last_Name: 'Apellidos:',
		Last_Name_Req: '¡El campo “Apellidos” es obligatorio!',
		Layout_WholeSystemTitle: '¡Danos tu opinión sobre el sistema!',
		Library_AllLabel: 'Todo',
		Library_Cancel: 'Cancelar',
		Library_ConfirmDelDocs: '¡Confirma la eliminación de los documentos seleccionados!',
		Library_NoDocSelected: 'Ningún documento ha sido seleccionado',
		Library_NoDocuments: 'No existen documentos disponibles',
		Library_NoLabels: 'No existen etiquetas',
		Library_NoLabelSelected: 'Ninguna etiqueta ha sido seleccionada',
		Library_NoMatchesFound: 'No se han encontrado coincidencias',
		Library_Save: 'Guardar',
		LineSpacingEnum_Large: 'Grande',
		LineSpacingEnum_Medium: 'Mediano',
		LineSpacingEnum_Small: 'Pequeño',
		LogIn_Carers_Click: '¿Eres intermediario? Haz click aquí',
		LogIn_Disclaimer: 'Open Book está en desarrollo. En esta página puedes ver la interfaz de usuario y un número todavía limitado de las herramientas. En cualquier caso muchas de las herramientas de simplificación del lenguaje todavía no están disponibles. Open Book estará completamente desarrollado a finales de 2014, mientras tanto, si necesitas más información por favor visita:',
		LogIn_Log_In_C: 'ENTRAR',
		LogIn_Log_In_Failed: 'Nombre de usuario o contraseña incorrectos.',
		LogIn_No_Account_Question: '¿No estás registrado?',
		LogIn_Password: 'Contraseña:',
		LogIn_Remember_Me: 'Recordar',
		LogIn_Sign_Up_C: 'REGISTRARSE',
		LogIn_User_Name: 'Nombre de usuario:',
		LogIn_User_Name_Req: '¡Por favor, indica un nombre de usuario!',
		Navigation_UserAccount: 'Cuenta de {0}',
		NotAuthorized_Message: '¡No estás autorizado para acceder a esa página!',
		Notification_DeleteDone: 'La notificación seleccionada ha sido borrada',
		Notification_ReplySent: 'Tu respuesta ha sido enviada',
		Notifications_Answer: 'Respuesta',
		Notifications_AnswerTo: 'Para',
		Notifications_ConfirmDelete: 'Confirma la eliminación de la notificación seleccionada',
		Notifications_Date: 'Fecha',
		Notifications_Document: 'Documento',
		Notifications_GoToDocument: 'Ir al documento',
		Notifications_LeaveMsg: 'El mensaje no ha sido enviado. ¿Seguro que quieres salir?',
		Notifications_Message: 'Mensaje',
		Notifications_NoNotifications: 'No tienes notificaciones nuevas.',
		Notifications_PleaseSelect: 'Por favor, selecciona una notificación',
		Notifications_SentOn: 'Enviado el',
		Notifications_Title: 'Tienes {0} notificaciones nuevas',
		Notifications_Users: 'Usuario',
		ObstacleFeedback_AcronymDefinitions: 'Esto es un acrónimo.',
		ObstacleFeedback_CoreferenceCorefentity: 'Esta palabra puede referirse a algo mencionado previamente en el texto. En su lugar, puede ser útil repetir el nombre completo de lo que se menciona.',
		ObstacleFeedback_CoreferenceDefiniteDescription: 'Esta palabra puede referirse a algo mencionado previamente en el texto. En su lugar, puede ser útil repetir el nombre completo de lo que se menciona.',
		ObstacleFeedback_FiglangsetFigLangDefinitions: 'Su significado real es diferente del significado literal de las palabras que la forman.',
		ObstacleFeedback_IdiomDefinitions: 'Esta es una frase hecha. Su significado real es diferente del significado literal de las palabras que la forman.',
		ObstacleFeedback_LongwordDefinitions: 'Esta es una palabra larga.',
		ObstacleFeedback_LongwordSynonyms: 'Esta es una palabra larga.',
		ObstacleFeedback_MultiwordDefinitions: 'Esta es una expresión compuesta por varias palabras.',
		ObstacleFeedback_MultiwordSynonyms: 'Esta es una expresión compuesta por varias palabras.',
		ObstacleFeedback_MultiwordWikiurls: 'Esta es una expresión compuesta por varias palabras.',
		ObstacleFeedback_PolysemicDefinitions: 'Esta es una palabra con varios significados y es ambigua.',
		ObstacleFeedback_PolysemicSynonym: 'Varias palabras tienen el mismo significado que esta palabra - tal vez una de ellas es más sencilla de comprender.',
		ObstacleFeedback_RareDefinitions: 'Esta es una palabra rara.',
		ObstacleFeedback_RareSynonyms: 'Varias palabras tienen el mismo significado que esta palabra -  tal vez una de ellas es más sencilla de comprender.',
		ObstacleFeedback_SpecializedDefinitions: 'Esta es una palabra especializada.',
		ObstacleFeedback_SpecializedSynonyms: 'Varias palabras tienen el mismo significado que esta palabra - tal vez una de ellas es más sencilla de comprender.',
		Password_Req: '¡El campo “Contraseña” es obligatorio!',
		Patients_NoPatient_Selected: '¡ No has seleccionado a ningún usuario!',
		Print_C: 'IMPRIMIR',
		Rep_Password: 'Repite la contraseña',
		ReplaceWordWithPicture: 'Sustituir la palabra por una imagen',
		ReplaceWordWithPicture_NoPictures: 'No existen imágenes disponibles',
		Req_Field: '* campo obligatorio',
		ReviewDocument_NextSentence: 'Siguiente frase',
		ReviewDocument_PrevSentence: 'Frase anterior',
		ServerCommunicationError: 'Error en la conexión al servidor',
		SignUp_First_Name: 'Nombre:',
		SignUp_Invalid_Mail: 'Formato de dirección de correo electrónico (email) incorrecto',
		SignUp_Invalid_Phone: 'Formato de número de teléfono incorrecto.',
		SignUp_Last_Name: 'Apellidos:',
		SignUp_Password: 'Contraseña:',
		SignUp_Sign_Up_C: 'REGISTRARSE',
		SignUp_Unaccepted_Format: '¡El fichero que estás intentando subir no tiene el formato correcto! Los formato válidos son: {0}.',
		SiteMaster_Account: 'Cuenta',
		SiteMaster_Documents: 'Documentos',
		SiteMaster_Documents_C: 'DOCUMENTOS',
		SiteMaster_Help: 'Ayuda',
		SiteMaster_Log_Out: 'Salir',
		SiteMaster_Log_Out_C: 'SALIR',
		SiteMaster_My_Account: 'Mi cuenta',
		SiteMaster_My_Account_C: 'MI CUENTA',
		SiteMaster_Notifications: 'Notificaciones',
		SiteMaster_Patients: 'Usuarios',
		SiteMaster_Preferences: 'Preferencias',
		SiteMaster_WhatIsNew: 'Novedades',
		Telephone: 'Teléfono:',
		Tests_NoQuestions: 'No existen preguntas asociadas a este test',
		UserAccount_BackgroundColor: 'Color de fondo',
		UserAccount_ConfirmDeleteLabel: '¿Deseas eliminar esta etiqueta?',
		UserAccount_Create: 'Crear',
		UserAccount_CreateLabel: 'Crear etiqueta',
		UserAccount_CreateTheme: 'Crear tema',
		UserAccount_CurrentTheme: 'Tema actual',
		UserAccount_Delete: 'eliminar',
		UserAccount_Edit: 'editar',
		UserAccount_EditLabel: 'Editar etiqueta',
		UserAccount_Email: 'Correo electrónico (email):',
		UserAccount_ExampleTemplate: 'Ejemplo de plantilla',
		UserAccount_FontColor: 'Color de fuente',
		UserAccount_FontOptions: 'Opciones de fuente',
		UserAccount_FontSize: 'Tamaño de la fuente',
		UserAccount_Gender: 'Sexo:',
		UserAccount_Highlight: 'Aumentar',
		UserAccount_HighlightColor: 'Color de resaltado',
		UserAccount_LabelName: 'Inserta el nombre de la etiqueta:',
		UserAccount_LabelNoName: '¡No se puede crear una etiqueta sin nombre!',
		UserAccount_Language: 'Idioma',
		UserAccount_LineSpacing: 'Interlineado',
		UserAccount_MagnifiedText: 'Texto magnificado',
		UserAccount_MagnifyColor: 'Color para aumentar',
		UserAccount_ManageLabels: 'Gestión de etiquetas',
		UserAccount_New: 'nuevo',
		UserAccount_NewLabel: 'Nueva etiqueta',
		UserAccount_OtherInfo: 'Otra información:',
		UserAccount_PickLabelColor: 'Escoge el color de la etiqueta:',
		UserAccount_PickLabelFontColor: 'Escoge el color de la fuente de la etiqueta:',
		UserAccount_Preview: 'Vista preliminar',
		UserAccount_PreviewTheme: 'Tema anterior',
		UserAccount_TextFont: 'Fuente del texto',
		UserAccount_TextWithHighlight: 'Texto con área resaltada',
		UserAccount_Themes: 'Temas',
		UserAccount_Toolbar: 'Barra de herramientas',
		Users_Delete: 'Borrar usuario',
		Users_DeleteConfirm: '¡Confirmar la eliminación del usuario seleccionado!',
		Users_DeleteError: 'Error al borrar el usuario seleccionado',
		Users_DeleteSuccess: 'El usuario seleccionado ha sido borrado',
		Users_Library: 'Biblioteca',
		Users_Register: 'Registrar usuario nuevo',
		Users_Title: 'Usuarios de {0}'
	};
})();