(function () {
    if (typeof window.Localization == 'undefined') window.Localization = { };
    window.Localization.resourcesBG = undefined;
    window.Localization.resourcesEN = {
		Browse_Dots: 'Browse ...',
		BrowserNotSupported_Body: 'Please upgrade your browser.',
		BrowserNotSupported_Title: 'The browser you are using is currently not supported.',
		Create_Account_C: 'CREATE ACCOUNT',
		CreateUserAccount_SuccessMessage: 'Your account has been successfully created. An email has been sent to you with detailed instructions on how to activate it.',
		CreateUserAccount_SuccessNote: 'NOTE: If you don\'t receive this email within an hour, please double check that your message is not in your Spam or Junk Mail folder. If this is not the case, please try to make a new registration.',
		DocumentEdit_AskCarerHint: 'Select problematic part of the text and press the button. Write your question in the text box below.',
		DocumentEdit_Bold: 'Bold',
		DocumentEdit_BoldHint: 'Select portion of the text then click here to make the selected part of the text bolder.',
		DocumentEdit_Close: 'CLOSE',
		DocumentEdit_Convert_Text_C: 'CONVERT',
		DocumentEdit_DocName: 'Document Name:',
		DocumentEdit_ExplainWithPictureHint: 'Select a word from the text and press the button. See the picture in the text box below.',
		DocumentEdit_ExplainWordHint: 'Select a word from the text and press the button. See the explanation in the text box below.',
		DocumentEdit_Highlight: 'Highlight',
		DocumentEdit_HighlightHint: 'Select part of the text and press the button.',
		DocumentEdit_Magnify: 'Magnify',
		DocumentEdit_MagnifyOffHint: 'Press the button to see the document in magnify mode.',
		DocumentEdit_MagnifyOnHint: 'You are in magnify mode. Use the mouse or the arrows to magnify sentences of the text. Press the button to turn it off.',
		DocumentEdit_NewLabel_Placeholder: 'Write label name here',
		DocumentEdit_Notes: 'Notes',
		DocumentEdit_NotesHint: 'Press the button and place your note in the text.',
		DocumentEdit_NotesOnHint: 'Place your note in the text. Write your note in the text box below.',
		DocumentEdit_Save_Result_C: 'SAVE',
		DocumentEdit_SelectText: 'Select text',
		DocumentEdit_SizeHint: 'Press the button and select a font size for your document.',
		DocumentEdit_TextInput_Placeholder: 'Write or copy and paste text here',
		DocumentEdit_Theme: 'Theme',
		DocumentEdit_ThemeHint: 'Press the button and select a theme for the document.',
		DocumentEdit_Underline: 'Underline',
		DocumentEdit_UnderlineHint: 'Select portion of the text then click here to place line under the selected part of the text.',
		DocumentEdit_UrlInput_Placeholder: 'Write or paste web address here',
		DocumentReview_Accept: 'Accept',
		DocumentReview_AddDefinition: 'Add definition',
		DocumentReview_AddImage: 'Add Image',
		DocumentReview_AltStructures: 'alternative structures',
		DocumentReview_Anaphoras: 'Anaphoras',
		DocumentReview_ConfirmReprocess: 'All your images and formatting will be lost for the current sentence. Do you want to proceed?',
		DocumentReview_ConfirmSentCancel: 'Please, confirmg canceling the sentence changes.',
		DocumentReview_ContactUser: 'Contact user',
		DocumentReview_CurrentSummary: 'Current summary:',
		DocumentReview_Custom: 'Custom',
		DocumentReview_Definitions: 'Definitions:',
		DocumentReview_Delete: 'delete:',
		DocumentReview_EditSummary: 'Edit summary',
		DocumentReview_Explain: 'Explain',
		DocumentReview_Hide: 'hide',
		DocumentReview_Images: 'Images:',
		DocumentReview_Insert: 'Insert',
		DocumentReview_InsertAnaphora: ' stands for...',
		DocumentReview_InsertDefinition: 'Insert definition',
		DocumentReview_InsertHyperlink: 'Insert hyperlink here:',
		DocumentReview_InsertImage: 'Insert image',
		DocumentReview_NoteText: 'Enter note:',
		DocumentReview_NotifSent: 'The notification has been sent successfuly.',
		DocumentReview_ObstacleOfType: 'The obstacle is of types:',
		DocumentReview_ObstaclesPlural: 'obstacles detected',
		DocumentReview_ObstaclesSingular: 'obstacle detected',
		DocumentReview_Original: 'original:',
		DocumentReview_OriginalSentence: 'Original sentence:',
		DocumentReview_Replace: 'Replace',
		DocumentReview_ReplaceWithSynonym: 'Replace with synonym',
		DocumentReview_Reprocess: 'Reprocess',
		DocumentReview_ReprocessDialogTitle: 'Confirm reprocess',
		DocumentReview_Retry: 'Try again',
		DocumentReview_SaveChanges: 'You have made changes to the document, that would not be saved upon leaving.',
		DocumentReview_SelectStructure: 'Select structure',
		DocumentReview_SendNotification: 'Send notification',
		DocumentReview_Show: 'show',
		DocumentReview_Split: 'split:',
		DocumentReview_Summary: 'Summary',
		DocumentReview_Synonyms: 'Synonyms',
		DocumentReview_TransformedSentence: 'Transformed sentence:',
		Documents_Add_C: 'ADD',
		Documents_Delete_C: 'DELETE',
		Documents_Edit_C: 'EDIT',
		Documents_New_Document_C: 'NEW DOCUMENT',
		Documents_NoDocument_Selected: 'No document selected!',
		Documents_Print_C: 'PRINT',
		Documents_Title: '{0}\'s Documents',
		DocumentsLibrary_ApplyLabel: 'Apply Label',
		DocumentsLibrary_ClearText: 'Clear text',
		DocumentsLibrary_CreateLabel: 'Create Label',
		DocumentsLibrary_Dialog_Label_Name: 'Enter label name:',
		DocumentsLibrary_Dialog_NoName: 'You cannot create label with no name!',
		DocumentsLibrary_Dialog_Pick_Color: 'Pick label color:',
		DocumentsLibrary_Dialog_Pick_Label_FontColor: 'Pick label font color:',
		DocumentsLibrary_Labels: 'Labels',
		DocumentsLibrary_ManageLabels: 'Manage labels',
		DocumentsLibrary_Pages: 'Pages:',
		DocumentsLibrary_RemoveLabels: 'Remove label',
		DocumentsLibrary_Search: 'Search:',
		DocumentTest_FinishDialogTitle: 'Test finished',
		DocumentTest_FinishText: 'Well done :)',
		DocumentTest_FinishTheTest: 'Finish the test',
		DocumentTest_NextQuestion: 'Next question',
		DocumentTest_Question: 'Question',
		Download: 'Download',
		EditDociment_NotificationRelatedDocument: 'Related Document',
		EditDocument_AddNote: 'Add note',
		EditDocument_AskCarer: 'Ask carer',
		EditDocument_AskCarerMessage: 'The text was sent to a carer. Here you can write your message',
		EditDocument_AskCarerSent: 'Your Request was sent successfully.',
		EditDocument_ContentSaved: 'Content saved',
		EditDocument_Conv_Text: 'Simplified Text',
		EditDocument_Done: 'Done',
		EditDocument_ExplainWithPicture: 'Explain with picture',
		EditDocument_ExplainWord: 'Explain Word',
		EditDocument_File: 'File',
		EditDocument_HereExplanation: 'Here is the explanation of the selected word',
		EditDocument_NewNoteText: 'This is your new note.',
		EditDocument_NoDefinition: 'No definition was found.',
		EditDocument_NoFile: 'Please select a file',
		EditDocument_NoteSaved: 'Your note was saved successfully',
		EditDocument_NoText: 'Please insert text',
		EditDocument_NoTextInput: 'Please insert text or URL or uplaod a text file!',
		EditDocument_NoTextSelected: 'Please select text for highlighting.',
		EditDocument_NotificationFrom: 'From',
		EditDocument_NotificationSubject: 'Subject',
		EditDocument_NotSaved: 'The changes you have made would not be saved if you leave the page now.',
		EditDocument_NoUrl: 'Please insert URL',
		EditDocument_Orig_Text: 'Original Text',
		EditDocument_Pictures: 'Pictures:',
		EditDocument_PrivateDocument: 'Private document',
		EditDocument_SampleThemeText: 'Sample theme text',
		EditDocument_Save_Document: 'Save document as',
		EditDocument_SelectAWord: 'Select a word',
		EditDocument_SelectPatient: 'Select patient:',
		EditDocument_SelectPatientError: 'You need to select a patient.',
		EditDocument_SelectProblematic: 'Select problematic part of the text',
		EditDocument_Send: 'Send',
		EditDocument_ShareWithCarer: 'Share with carer',
		EditDocument_ShowMultiwords: 'Show Multiwords',
		EditDocument_ShowMultiwordsHint: 'See all multiword expressions and idioms in the text',
		EditDocument_ShowObstacles: 'Show Obstacles',
		EditDocument_ShowObstaclesHint: 'See all difficult words in the text',
		EditDocument_Size: 'Size:',
		EditDocument_SummaryHint: 'Review summary of the text in the text box below.',
		EditDocument_Take_The_Test: 'Take the test',
		EditDocument_Text: 'Text',
		EditDocument_URL_C: 'URL',
		EditPatientDetails_Additional_Information: 'Additional information:',
		EditPatientDetails_Age: 'Age:',
		EditPatientDetails_Age_Invalid: 'The supplied age must be between 1 and 100',
		EditPatientDetails_Edit_Patient: 'Edit patient',
		EditPatientDetails_Gender: 'Gender:',
		EditPatientDetails_Not_Same_Password: 'The password does not match with it\'s confirmation field.',
		EditPatientDetails_TabAccount: 'Profile information',
		EditPatientDetails_TabPreferences: 'Preferences',
		EditPatientDetails_Update_Account_C: 'UPDATE ACCOUNT',
		Email: 'Email:',
		Email_Req: 'The field "Email" is required!',
		Error_ButtonBack: 'Back',
		Error_GeneralError: 'Unexpected error occured. Please, navigate back and try again!',
		Error_List: 'Error list:',
		ExplainWord: 'Explain word',
		ExplainWord_NoPictures: 'There are no explanations of the given word.',
		Explanations_ContinueToTheText: 'Continue to the text',
		Feedback_ErrorEmpty: 'You cannot send an empty feedback message!',
		Feedback_RecepientError: 'The mail could not be delivered to the recepient, please try again later!',
		Feedback_SendFeedback: 'Send system feedback',
		Feedback_SendSentence: 'Leave your feedback on the current sentence here',
		Feedback_SendSentFeedback: 'Send sentence feedback',
		Feedback_SMTPError: 'SMTP error occured while attempting to send your message, try sending it again later.',
		Feedback_Success: 'Your feeedback has been sent successfuly',
		FileUpload_FileNotCorrectType: 'The file you selected for upload is not in the correct format!',
		FileUpload_FileTooBig: 'The file you selected is too big. Choose file smaller than {0}.',
		First_Name: 'First name:',
		First_Name_Req: 'The field "First name" is required!',
		GenderEnum_Female: 'Female',
		GenderEnum_Male: 'Male',
		Help_NotAvailable: 'Help not currently available.',
		Highlight: 'Highlight',
		Last_Name: 'Last name:',
		Last_Name_Req: 'The field "Last name" is required!',
		Layout_WholeSystemTitle: 'Leave your feedback on the whole system',
		Library_AllLabel: 'All',
		Library_Cancel: 'Cancel',
		Library_ConfirmDelDocs: 'Confirm deleting the selected documents!',
		Library_NoDocSelected: 'No document selected',
		Library_NoDocuments: 'No documents available',
		Library_NoLabels: 'No labels',
		Library_NoLabelSelected: 'No label selected',
		Library_NoMatchesFound: 'No matches found',
		Library_Save: 'Save',
		LineSpacingEnum_Large: 'Large',
		LineSpacingEnum_Medium: 'Medium',
		LineSpacingEnum_Small: 'Small',
		LogIn_Carers_Click: 'Carers click here',
		LogIn_ContactUs: 'If you would like to test the system please contact us.',
		LogIn_Disclaimer: 'Open Book is still in development. On this site you can see the user interface and a limited number of the tool\'s functions, however the language simplification functions are not yet available. Open Book will be completed at the end of 2014. In the meantime, if you would like more information, please visit:',
		LogIn_ForgotPassword: 'Forgot your password?',
		LogIn_Log_In_C: 'LOG IN',
		LogIn_Log_In_Failed: 'Wrong email or password.',
		LogIn_No_Account_Question: 'Don\'t have an account?',
		LogIn_Password: 'Password:',
		LogIn_Remember_Me: 'Remember me',
		LogIn_Sign_Up_C: 'SIGN UP',
		LogIn_User_Name: 'Email:',
		LogIn_User_Name_Req: 'Please provide user name!',
		Navigation_UserAccount: '{0}\'s Account',
		NotAuthorized_Message: 'You have not been authorized to access that page!',
		Notification_DeleteDone: 'The selected notification was deleted successfuly',
		Notification_ReplySent: 'Your reply was sent successfully',
		Notifications_Answer: 'Answer',
		Notifications_AnswerTo: 'To',
		Notifications_ConfirmDelete: 'Confirm deleting the selected notification!',
		Notifications_Date: 'Date',
		Notifications_Document: 'Document',
		Notifications_GoToDocument: 'Go to Document',
		Notifications_LeaveMsg: 'You haven\'t sent the message. Are you sure you want to leave?',
		Notifications_Message: 'Message',
		Notifications_NoNotifications: 'You have no notifications.',
		Notifications_PleaseSelect: 'Please, select notification',
		Notifications_SentOn: 'Sent on',
		Notifications_Title: 'You have {0} new notifications',
		Notifications_Users: 'Users',
		ObstacleFeedback_AcronymDefinitions: 'This is acronym.',
		ObstacleFeedback_CoreferenceCorefentity: 'This word may refer to something previously mentioned in the text. It may be useful to repeat the full name of that thing, instead.',
		ObstacleFeedback_CoreferenceDefiniteDescription: 'This word may refer to something previously mentioned in the text. It may be useful to repeat the full name of that thing, instead.',
		ObstacleFeedback_FiglangsetFigLangDefinitions: 'The real meaning of this phrase is different from the literal meanings of the words inside it.',
		ObstacleFeedback_IdiomDefinitions: 'This is an idiom - its real meaning is different from the literal meanings of the words inside it.',
		ObstacleFeedback_LongwordDefinitions: 'This is a long word.',
		ObstacleFeedback_LongwordSynonyms: 'This is a long word.',
		ObstacleFeedback_MultiwordDefinitions: 'This is an expression which consists of several words.',
		ObstacleFeedback_MultiwordSynonyms: 'This is an expression which consists of several words.',
		ObstacleFeedback_MultiwordWikiurls: 'This is an expression which consists of several words.',
		ObstacleFeedback_PolysemicDefinitions: 'This word has several meanings and is ambiguous.',
		ObstacleFeedback_PolysemicSynonym: 'Several other words have the same meaning as this word - perhaps one of them is easier to understand.',
		ObstacleFeedback_RareDefinitions: 'This is a rare word.',
		ObstacleFeedback_RareSynonyms: 'Several other words have the same meaning as this word - perhaps one of them is easier to understand.',
		ObstacleFeedback_SpecializedDefinitions: 'This is a specialised word.',
		ObstacleFeedback_SpecializedSynonyms: 'Several other words have the same meaning as this word - perhaps one of them is easier to understand.',
		Password_Req: 'The field "Password" is required!',
		PasswordRequest_BackToLogIn: 'Back to log in',
		PasswordRequest_EnterEmail: 'Enter your account email here:',
		PasswordRequest_RetrievePassword: 'Retrieve password',
		PasswordRequest_Success: 'The password you requested for the specified email address has been successfuly sent. Please check your email.',
		Patients_NoPatient_Selected: 'No patient selected!',
		Print_C: 'PRINT',
		Rep_Password: 'Repeat password:',
		ReplaceWordWithPicture_NoPictures: 'There are no pictures available.',
		Req_Field: '* required field',
		ReviewDocument_NextSentence: 'Next sentence',
		ReviewDocument_PrevSentence: 'Previous sentence',
		ServerCommunicationError: 'Error occured while connecting to the server.',
		SignUp_First_Name: 'First name:',
		SignUp_Invalid_Mail: 'Invalid email format.',
		SignUp_Invalid_Phone: 'Invalid phone format.',
		SignUp_Last_Name: 'Last name:',
		SignUp_Password: 'Password:',
		SignUp_Sign_Up_C: 'SIGN UP',
		SignUp_Unaccepted_Format: 'The file you are trying to upload is not of valid format! The supported formats are: {0}.',
		SiteMaster_Account: 'Account',
		SiteMaster_Documents: 'Documents',
		SiteMaster_Documents_C: 'DOCUMENTS',
		SiteMaster_Help: 'Help',
		SiteMaster_Log_Out: 'Log out',
		SiteMaster_Log_Out_C: 'LOG OUT',
		SiteMaster_My_Account: 'My Account',
		SiteMaster_My_Account_C: 'MY ACCOUNT',
		SiteMaster_Notifications: 'Notifications',
		SiteMaster_Patients: 'Users',
		SiteMaster_Preferences: 'Preferences',
		SiteMaster_WhatIsNew: 'What\'s new',
		Telephone: 'Telephone:',
		Tests_NoQuestions: 'There are no questions within this test',
		UserAccount_BackgroundColor: 'Background color',
		UserAccount_ConfirmDeleteLabel: 'Do you want to delete this label?',
		UserAccount_Create: 'Create',
		UserAccount_CreateLabel: 'Create Label',
		UserAccount_CreateTheme: 'Create Theme',
		UserAccount_CurrentTheme: 'Current theme',
		UserAccount_Delete: 'Delete',
		UserAccount_Edit: 'Edit',
		UserAccount_EditLabel: 'Edit label',
		UserAccount_Email: 'Email:',
		UserAccount_ExampleTemplate: 'Example of template',
		UserAccount_FontColor: 'Font color',
		UserAccount_FontOptions: 'Font Options',
		UserAccount_FontSize: 'Font Size',
		UserAccount_Gender: 'Gender',
		UserAccount_Highlight: 'Highlight',
		UserAccount_HighlightColor: 'Highlight color',
		UserAccount_LabelName: 'Enter label name:',
		UserAccount_LabelNoName: 'You cannot create label with no name!',
		UserAccount_Language: 'Language',
		UserAccount_LineSpacing: 'Line Spacing',
		UserAccount_MagnifiedText: 'Magnified text',
		UserAccount_MagnifyColor: 'Magnify Color',
		UserAccount_ManageLabels: 'Manage labels',
		UserAccount_New: 'new',
		UserAccount_NewLabel: 'New Label',
		UserAccount_OtherInfo: 'Some other information:',
		UserAccount_PickLabelColor: 'Pick label color:',
		UserAccount_PickLabelFontColor: 'Pick label font color:',
		UserAccount_Preview: 'Preview',
		UserAccount_PreviewTheme: 'Preview theme',
		UserAccount_TextFont: 'Text Font',
		UserAccount_TextWithHighlight: 'Text with highlighted part',
		UserAccount_Themes: 'Themes',
		UserAccount_Toolbar: 'Toolbar',
		Users_Delete: 'Delete user',
		Users_DeleteConfirm: 'Confirm deleting the selected user!',
		Users_DeleteError: 'Error deleting the selected user',
		Users_DeleteSuccess: 'The selected user was deleted successfuly',
		Users_Library: 'Library',
		Users_NoSelected: 'Please, select user',
		Users_Register: 'Register new user',
		Users_Title: '{0}\'s users'
	};
    window.Localization.resourcesES = undefined;
})();