(function () {
    if (typeof window.Localization == 'undefined') window.Localization = { };
    window.Localization.resourcesBG = {
		Browse_Dots: 'Прегледай…',
		BrowserNotSupported_Body: 'Моля актуализирайте браузъра си',
		BrowserNotSupported_Title: 'Тази версия на браузъра не се поддържа.',
		Create_Account_C: 'СЪЗДАЙ ПРОФИЛ',
		CreateUserAccount_SuccessMessage: 'Вашият профил беше създаден успешно. Изпратен е E-mail с инструкции как да го активирате',
		CreateUserAccount_SuccessNote: 'Забележка: Ако до един час не получите E-mail, моля проверете дали той не се намира в папките Junk или Spam. Ако случаят не е такъв, моля опитайте да направите нова регистрация!',
		DocumentEdit_AskCarerHint: 'Изберете проблемна част от текста и натиснете бутона. Напишете въпроса си в текстовото поле долу.',
		DocumentEdit_Bold: 'Потъмни',
		DocumentEdit_BoldHint: 'Изберете част от текста и натиснете бутона, за да потъмните текста.',
		DocumentEdit_Close: 'ЗАТВОРИ',
		DocumentEdit_Convert_Text_C: 'ПРЕРАБОТИ',
		DocumentEdit_DocName: 'Име на документа:',
		DocumentEdit_ExplainWithPictureHint: 'Изберете дума от текста и натиснете бутона. Картинката можете да видите в текстовото поле долу.',
		DocumentEdit_ExplainWordHint: 'Изберете дума от текста и натиснете бутона. Обяснението можете да видите в текстовото поле долу.',
		DocumentEdit_Highlight: 'Маркирай',
		DocumentEdit_HighlightHint: 'Изберете част от текста и натиснете бутона.',
		DocumentEdit_Magnify: 'Фокусирай',
		DocumentEdit_MagnifyOffHint: 'Натиснете бутона, за да видите документа в режим "Фокусирай".',
		DocumentEdit_MagnifyOnHint: 'Вие сте в режим "Фокусирай". Използвайте мишката или стрелките на клавиатурата, за да се фокусирате върху изречение. Натиснете повторно бутона, за да изключите режим "Фокусирай".',
		DocumentEdit_NewLabel_Placeholder: 'Напишете името на етикета тук.',
		DocumentEdit_Notes: 'Бележка',
		DocumentEdit_NotesHint: 'Натиснете бутона и поставете бележката в текста.',
		DocumentEdit_NotesOnHint: 'Поставете бележката в текста. Напишете текста на бележката в текстовото поле най-долу.',
		DocumentEdit_Save_Result_C: 'ЗАПАЗИ',
		DocumentEdit_SelectText: 'Изберете текст',
		DocumentEdit_SizeHint: 'Натиснете бутона и изберете размер на шрифта от падащия списък',
		DocumentEdit_TextInput_Placeholder: 'Напишете или копирайте и поставете текст тук.',
		DocumentEdit_Theme: 'Тема',
		DocumentEdit_ThemeHint: 'Натиснете бутона и изберете тема за документа.',
		DocumentEdit_Underline: 'Подчертай',
		DocumentEdit_UnderlineHint: 'Изберете текст и натиснете бутона, за да подчертаете избрания текст.',
		DocumentEdit_UrlInput_Placeholder: 'Напишете или копирайте и поставете уеб адрес тук.',
		DocumentReview_Accept: 'Одобри',
		DocumentReview_AddDefinition: 'Добави дефиниция',
		DocumentReview_AddImage: 'Добавяне на снимка',
		DocumentReview_AltStructures: 'алтернативни структури',
		DocumentReview_Anaphoras: 'Анафори',
		DocumentReview_ConfirmReprocess: 'Добавените от вас картинки и форматирания ще бъдат изгубени за текущото изречение. Съгласни ли сте да продължите?',
		DocumentReview_ConfirmSentCancel: 'Please, confirmg canceling the sentence changes.',
		DocumentReview_ContactUser: 'Изпрати',
		DocumentReview_CurrentSummary: 'Резюме в момента:',
		DocumentReview_Custom: 'Собствена',
		DocumentReview_Definitions: 'Дефиниции:',
		DocumentReview_Delete: 'изтриване:',
		DocumentReview_EditSummary: 'Редакция на резюмето',
		DocumentReview_Explain: 'Обясни',
		DocumentReview_Hide: 'скрий',
		DocumentReview_Images: 'Изображения:',
		DocumentReview_Insert: 'Вмъкни',
		DocumentReview_InsertAnaphora: ' се отнася за...',
		DocumentReview_InsertDefinition: 'Вмъкни дефиниция',
		DocumentReview_InsertHyperlink: 'Въведете хиперлинк тук:',
		DocumentReview_InsertImage: 'Вмъкни снимка',
		DocumentReview_NoteText: 'Въведете бележката:',
		DocumentReview_NotifSent: 'Известието е изпратено успешно.',
		DocumentReview_ObstacleOfType: 'Препятствието е от тип:',
		DocumentReview_ObstaclesPlural: 'препятствия засечени',
		DocumentReview_ObstaclesSingular: 'засечени препятствия',
		DocumentReview_Original: 'оригинално:',
		DocumentReview_OriginalSentence: 'Оригинално изречение:',
		DocumentReview_Replace: 'Замени',
		DocumentReview_ReplaceWithSynonym: 'Замести със синоним',
		DocumentReview_Reprocess: 'Анализирай',
		DocumentReview_ReprocessDialogTitle: 'Потвърдете анализирането',
		DocumentReview_Retry: 'Опитай отново',
		DocumentReview_SaveChanges: 'Извършили сте промени по документа, които няма да бъдат записани при изход от станицата.',
		DocumentReview_SelectStructure: 'Избери структура',
		DocumentReview_SendNotification: 'Изпрати съобщение',
		DocumentReview_Show: 'покажи',
		DocumentReview_Split: 'разделяне:',
		DocumentReview_Summary: 'Резюме',
		DocumentReview_Synonyms: 'Синоними',
		DocumentReview_TransformedSentence: 'Трансформирано изречение:',
		Documents_Add_C: 'ДОБАВИ',
		Documents_Delete_C: 'ИЗТРИЙ',
		Documents_Edit_C: 'РЕДАКТИРАЙ',
		Documents_New_Document_C: 'НОВ ДОКУМЕНТ',
		Documents_NoDocument_Selected: 'Не сте избрали документ.',
		Documents_Print_C: 'ПРИНТИРАЙ',
		Documents_Title: 'Документите на {0}',
		DocumentsLibrary_ApplyLabel: 'Приложи етикет',
		DocumentsLibrary_ClearText: 'Изчисти текста',
		DocumentsLibrary_CreateLabel: 'Създай етикет',
		DocumentsLibrary_Dialog_Label_Name: 'Въведи име на етикет:',
		DocumentsLibrary_Dialog_NoName: 'Не можете да създадете етикет без име.',
		DocumentsLibrary_Dialog_Pick_Color: 'Избери цвят за етикета:',
		DocumentsLibrary_Dialog_Pick_Label_FontColor: 'Избери цвят на текста:',
		DocumentsLibrary_Labels: 'Етикети',
		DocumentsLibrary_ManageLabels: 'Управление на етикети',
		DocumentsLibrary_Pages: 'Страници:',
		DocumentsLibrary_RemoveLabels: 'Премахни етикет',
		DocumentsLibrary_Search: 'Търси:',
		DocumentTest_FinishDialogTitle: 'Тестът е завършен',
		DocumentTest_FinishText: 'Браво :)',
		DocumentTest_FinishTheTest: 'Завърши теста',
		DocumentTest_NextQuestion: 'Следващ въпрос',
		DocumentTest_Question: 'Въпрос',
		Download: 'Свали',
		EditDociment_NotificationRelatedDocument: 'Относно документ:',
		EditDocument_AddNote: 'Добави бележка',
		EditDocument_AskCarer: 'Попитай специалист',
		EditDocument_AskCarerMessage: 'Този текст беше изпратен на специалиста. Тук можете да оставите съобщение.',
		EditDocument_AskCarerSent: 'Вашето запитване беше изпратено успешно.',
		EditDocument_ContentSaved: 'Съдържанието е запазено.',
		EditDocument_Conv_Text: 'Преработен текст',
		EditDocument_Done: 'Готово',
		EditDocument_ExplainWithPicture: 'Обясни с картинка',
		EditDocument_ExplainWord: 'Обясни думата',
		EditDocument_File: 'Файл',
		EditDocument_HereExplanation: 'Това е обяснението на избраната дума.',
		EditDocument_NewNoteText: 'Това е новата ви бележка.',
		EditDocument_NoDefinition: 'Не беше намерена дефиниция.',
		EditDocument_NoFile: 'Моля, изберете файл.',
		EditDocument_NoteSaved: 'Вашата бележка беше запазена успешно.',
		EditDocument_NoText: 'Моля, въведете текст.',
		EditDocument_NoTextInput: 'Моля, въведете текст или URL или текстови файл.',
		EditDocument_NoTextSelected: 'Моля, изберете текст за маркиране.',
		EditDocument_NotificationFrom: 'От:',
		EditDocument_NotificationSubject: 'На тема',
		EditDocument_NotSaved: 'Направените промени няма да бъдат запазани, ако затворите страницата.',
		EditDocument_NoUrl: 'Моля, въведете уеб адрес.',
		EditDocument_Orig_Text: 'Оригинален текст',
		EditDocument_Pictures: 'Картинки:',
		EditDocument_PrivateDocument: 'Личен документ',
		EditDocument_SampleThemeText: 'Примерна тема',
		EditDocument_Save_Document: 'Име на документа:',
		EditDocument_SelectAWord: 'Изберете дума',
		EditDocument_SelectPatient: 'Изберете потребител:',
		EditDocument_SelectPatientError: 'Трябва да изберете потребител.',
		EditDocument_SelectProblematic: 'Изберете проблемна част от текста.',
		EditDocument_Send: 'Изпрати',
		EditDocument_ShareWithCarer: 'Сподели със специалист',
		EditDocument_ShowMultiwords: 'Покажи фрази',
		EditDocument_ShowMultiwordsHint: 'Покажи всички съставни думи и идиоми в текста',
		EditDocument_ShowObstacles: 'Покажи препятствия',
		EditDocument_ShowObstaclesHint: 'Покажи всички трудни думи в текста',
		EditDocument_Size: 'Размер',
		EditDocument_SummaryHint: 'Прегледайте резюмето на текста в кутийка от долу.',
		EditDocument_Take_The_Test: 'Започни тест',
		EditDocument_Text: 'Текст',
		EditDocument_URL_C: 'Уеб адрес',
		EditPatientDetails_Additional_Information: 'Допълнителна информация:',
		EditPatientDetails_Age: 'Възраст:',
		EditPatientDetails_Age_Invalid: 'Възрастта трябва да бъде число между 1 и 100.',
		EditPatientDetails_Edit_Patient: 'Редакция на потребител',
		EditPatientDetails_Gender: 'Пол',
		EditPatientDetails_Not_Same_Password: 'Паролата на отговаря.',
		EditPatientDetails_TabAccount: 'Профилна информация',
		EditPatientDetails_TabPreferences: 'Предпочитания',
		EditPatientDetails_Update_Account_C: 'ПОТВЪРДИ ПРОМЕНИТЕ',
		Email: 'Е-поща',
		Email_Req: 'Полето "Е-поща" е задължително.',
		Error_ButtonBack: 'Обратно',
		Error_GeneralError: 'Изникна неочаквана грешка. Моля, върнете се обратно и опитайте отново.',
		Error_List: 'Списък с грешки:',
		ExplainWord: 'Обясни думата',
		ExplainWord_NoPictures: 'Няма въведени обяснения за тази дума.',
		Explanations_ContinueToTheText: 'Продължете към текста',
		Feedback_ErrorEmpty: 'Не можете да изпращате празно съобщение!',
		Feedback_RecepientError: 'Писмото не можа да бъде изпратено до получателя, моля опитайте по-късно!',
		Feedback_SendFeedback: 'Изпрати съобщение за обратна връзка за системата',
		Feedback_SendSentence: 'Оставете вашето съобщение за обратна връзка за изречение тук',
		Feedback_SendSentFeedback: 'Изпрати съобщение за обрана връзка за изречение',
		Feedback_SMTPError: 'SMTP грешка настъпи при опит за изпращане на съобщението, моля опитайте по-късно!',
		Feedback_Success: 'Вашето съобщение за обратна връзка беше изпратено успешно',
		FileUpload_FileNotCorrectType: 'Избраният файл не е в подходящ формат.',
		FileUpload_FileTooBig: 'Избраният файл е твърде голям. Изберете файл с размер, по-малък от {0}.',
		First_Name: 'Име:',
		First_Name_Req: 'Полето "Име" е задължително.',
		GenderEnum_Female: 'Жена',
		GenderEnum_Male: 'Мъж',
		Help_NotAvailable: 'Няма налична помощ в момента.',
		Highlight: 'Маркирай',
		Last_Name: 'Фамилия:',
		Last_Name_Req: 'Полето "Фамилия" е задължително.',
		Layout_WholeSystemTitle: 'Оставете обратна връзка върху цялата система',
		Library_AllLabel: 'Всички',
		Library_Cancel: 'Затвори',
		Library_ConfirmDelDocs: 'Потвърдете изтриването на избраните документи.',
		Library_NoDocSelected: 'Изберете документ',
		Library_NoDocuments: 'Няма въведени документ',
		Library_NoLabels: 'Няма въведени етикети',
		Library_NoLabelSelected: 'Изберете етикет',
		Library_NoMatchesFound: 'Няма намерени съвпадения',
		Library_Save: 'Запази',
		LineSpacingEnum_Large: 'Голямо',
		LineSpacingEnum_Medium: 'Средно',
		LineSpacingEnum_Small: 'Малко',
		LogIn_Carers_Click: 'Регистация на специалисти',
		LogIn_ContactUs: 'Ако бихте желали да тествате системата, моля свържете се с нас.',
		LogIn_Disclaimer: 'Open Book е все още в процес на разработка. На този сайт можете да видите изгледа и част от функционалностите на системата, като имате предвид, че езиковото опростяване все още не е готово. Open Book ще бъде приключен в края на 2014. При необходимост от допълнителна информация, моля, посетете:',
		LogIn_ForgotPassword: 'Забравена парола?',
		LogIn_Log_In_C: 'ВЛИЗАНЕ',
		LogIn_Log_In_Failed: 'Неправилен имейл адрес или парола.',
		LogIn_No_Account_Question: 'Нямате регистрация?',
		LogIn_Password: 'Парола:',
		LogIn_Remember_Me: 'Запомни ме',
		LogIn_Sign_Up_C: 'РЕГИСТРАЦИЯ',
		LogIn_User_Name: 'Е-поща:',
		LogIn_User_Name_Req: 'Моля въведете е-поща.',
		Navigation_UserAccount: 'Профил на {0}',
		NotAuthorized_Message: 'Нямате достъп до страницата.',
		Notification_DeleteDone: 'Избраното известие беше изтрито успешно',
		Notification_ReplySent: 'Вашият отговор беше изпратен успешно',
		Notifications_Answer: 'Отговор',
		Notifications_AnswerTo: 'До',
		Notifications_ConfirmDelete: 'Потвърдете изтриването на избрания документ!',
		Notifications_Date: 'Дата',
		Notifications_Document: 'Документ',
		Notifications_GoToDocument: 'Иди на Документа',
		Notifications_LeaveMsg: 'Не сте изпратили съобщението. Потвърдете излизане от страницата!',
		Notifications_Message: 'Съобщение',
		Notifications_NoNotifications: 'Нямате известия.',
		Notifications_PleaseSelect: 'Моля, изберете известие',
		Notifications_SentOn: 'Изпратен на',
		Notifications_Title: 'Имате {0} нови известия',
		Notifications_Users: 'Потребители',
		ObstacleFeedback_AcronymDefinitions: 'Това е абревиатура.',
		ObstacleFeedback_CoreferenceCorefentity: 'Може би става дума за нещо, споменато в текста по-рано. Използвайте пълното му наименование за улеснение.',
		ObstacleFeedback_CoreferenceDefiniteDescription: 'Може би става дума за нещо, споменато в текста по-рано. Използвайте пълното му наименование за улеснение.',
		ObstacleFeedback_FiglangsetFigLangDefinitions: 'Истинското значение на израза е различно от буквалното значение на съставящите го думи.',
		ObstacleFeedback_IdiomDefinitions: 'Това е идиом – истинското му значение е различно от буквалното значение на съставящите го думи.',
		ObstacleFeedback_LongwordDefinitions: 'Дълга дума.',
		ObstacleFeedback_LongwordSynonyms: 'Дълга дума.',
		ObstacleFeedback_MultiwordDefinitions: 'Изразът се състои от няколко думи.',
		ObstacleFeedback_MultiwordSynonyms: 'Изразът се състои от няколко думи.',
		ObstacleFeedback_MultiwordWikiurls: 'Изразът се състои от няколко думи.',
		ObstacleFeedback_PolysemicDefinitions: 'Думата има няколко значения.',
		ObstacleFeedback_PolysemicSynonym: 'Съществуват по-лесни синоними на тази дума, с които да бъде заменена.',
		ObstacleFeedback_RareDefinitions: 'Рядкосрещана дума.',
		ObstacleFeedback_RareSynonyms: 'Съществуват по-лесни синоними на тази дума, с които може да бъде заменена.',
		ObstacleFeedback_SpecializedDefinitions: 'Специализирана дума.',
		ObstacleFeedback_SpecializedSynonyms: 'Съществуват по-лесни синоними на тази дума, с които може да бъде заменена.',
		Password_Req: 'Полето "Парола" е задължително.',
		PasswordRequest_BackToLogIn: 'Обратно към вход в системата',
		PasswordRequest_EnterEmail: 'Въведете email-а на вашия акаунт:',
		PasswordRequest_RetrievePassword: 'Получи парола',
		PasswordRequest_Success: 'Паролата, която поискахте за избрания email, беше успешно изпратена. Моля, проверете си пощата.',
		Patients_NoPatient_Selected: 'Не сте избрали потребител.',
		Print_C: 'ПРИНТИРАЙ',
		Rep_Password: 'Повтори парола:',
		ReplaceWordWithPicture_NoPictures: 'Няма картинки за избраната дума',
		Req_Field: '*задължително поле',
		ReviewDocument_NextSentence: 'Следващо изречение',
		ReviewDocument_PrevSentence: 'Предишно изречение',
		ServerCommunicationError: 'Възникна проблем при свързването със сървъра.',
		SignUp_First_Name: 'Име:',
		SignUp_Invalid_Mail: 'Невалиден формат на е-поща.',
		SignUp_Invalid_Phone: 'Невалиден тел. номер.',
		SignUp_Last_Name: 'Фамилия:',
		SignUp_Password: 'Парола',
		SignUp_Sign_Up_C: 'РЕГИСТРАЦИЯ',
		SignUp_Unaccepted_Format: 'Избраният формат на файл не се поддържа. Изберете файл във формат {0}.',
		SiteMaster_Account: 'Профил',
		SiteMaster_Documents: 'Документи',
		SiteMaster_Documents_C: 'ДОКУМЕНТИ',
		SiteMaster_Help: 'Помощ',
		SiteMaster_Log_Out: 'Изход',
		SiteMaster_Log_Out_C: 'ИЗХОД',
		SiteMaster_My_Account: 'Моят профил',
		SiteMaster_My_Account_C: 'МОЯТ ПРОФИЛ',
		SiteMaster_Notifications: 'Известия',
		SiteMaster_Patients: 'Потребители',
		SiteMaster_Preferences: 'Предпочитания',
		SiteMaster_WhatIsNew: 'Ново',
		Telephone: 'Телефон:',
		Tests_NoQuestions: 'Няма въпроси',
		UserAccount_BackgroundColor: 'Цвят на фона',
		UserAccount_ConfirmDeleteLabel: 'Искате ли да изтриете този етикет?',
		UserAccount_Create: 'Създай',
		UserAccount_CreateLabel: 'Създай етикет',
		UserAccount_CreateTheme: 'Създай тема',
		UserAccount_CurrentTheme: 'Избрана тема',
		UserAccount_Delete: 'Изтриване',
		UserAccount_Edit: 'Редакция',
		UserAccount_EditLabel: 'Редакция на етикет',
		UserAccount_Email: 'Е-поща:',
		UserAccount_ExampleTemplate: 'Примерна тема',
		UserAccount_FontColor: 'Цвят на шрифта',
		UserAccount_FontOptions: 'Опции на шрифтовете',
		UserAccount_FontSize: 'Големина на шрифта',
		UserAccount_Gender: 'Пол',
		UserAccount_Highlight: 'Маркиране',
		UserAccount_HighlightColor: 'Цвят на маркера',
		UserAccount_LabelName: 'Въведи име на етикет:',
		UserAccount_LabelNoName: 'Не можете да създадете етикет без име.',
		UserAccount_Language: 'Език',
		UserAccount_LineSpacing: 'Разстояние между редовете',
		UserAccount_MagnifiedText: 'Усилен текст',
		UserAccount_MagnifyColor: 'Цвят на фокусиране',
		UserAccount_ManageLabels: 'Управление на етикетите',
		UserAccount_New: 'нови',
		UserAccount_NewLabel: 'Нов етикет',
		UserAccount_OtherInfo: 'Друга информация:',
		UserAccount_PickLabelColor: 'Избери цвят на етикет:',
		UserAccount_PickLabelFontColor: 'Избери цвят на фона:',
		UserAccount_Preview: 'Преглед',
		UserAccount_PreviewTheme: 'Преглед на тема',
		UserAccount_TextFont: 'Шрифт',
		UserAccount_TextWithHighlight: 'Текст с осветена част',
		UserAccount_Themes: 'Теми',
		UserAccount_Toolbar: 'Лента с инструменти',
		Users_Delete: 'Изтрий потребител',
		Users_DeleteConfirm: 'Потвърдете изтриването на потребителя!',
		Users_DeleteError: 'Грешка при изтриване на избрания потребител',
		Users_DeleteSuccess: 'Избраният потребител е изтрит успешно',
		Users_Library: 'Библиотека',
		Users_NoSelected: 'Моля, изберете потребител',
		Users_Register: 'Регистрирайте нов потребител',
		Users_Title: 'Потребители на {0}'
	};
    window.Localization.resourcesEN = undefined;
    window.Localization.resourcesES = undefined;
})();