//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.10 at 08:50:18 PM CET 
//


package es.ujaen.sinai.first.io.xml.nlptoolsshare;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.ujaen.sinai.nlptoolsshare package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Token_QNAME = new QName("http://sinai.ujaen.es/nlptoolsshare", "token");
    private final static QName _Text_QNAME = new QName("http://sinai.ujaen.es/nlptoolsshare", "text");
    private final static QName _Document_QNAME = new QName("http://sinai.ujaen.es/nlptoolsshare", "document");
    private final static QName _Nlptoolsshare_QNAME = new QName("http://sinai.ujaen.es/nlptoolsshare", "nlptoolsshare");
    private final static QName _Tokens_QNAME = new QName("http://sinai.ujaen.es/nlptoolsshare", "tokens");
    private final static QName _Sentence_QNAME = new QName("http://sinai.ujaen.es/nlptoolsshare", "sentence");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.ujaen.sinai.nlptoolsshare
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DocumentType }
     * 
     */
    public DocumentType createDocumentType() {
        return new DocumentType();
    }

    /**
     * Create an instance of {@link TokenType }
     * 
     */
    public TokenType createTokenType() {
        return new TokenType();
    }

    /**
     * Create an instance of {@link SentenceType }
     * 
     */
    public SentenceType createSentenceType() {
        return new SentenceType();
    }

    /**
     * Create an instance of {@link TokensType }
     * 
     */
    public TokensType createTokensType() {
        return new TokensType();
    }

    /**
     * Create an instance of {@link NlptoolsshareType }
     * 
     */
    public NlptoolsshareType createNlptoolsshareType() {
        return new NlptoolsshareType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TokenType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sinai.ujaen.es/nlptoolsshare", name = "token")
    public JAXBElement<TokenType> createToken(TokenType value) {
        return new JAXBElement<TokenType>(_Token_QNAME, TokenType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sinai.ujaen.es/nlptoolsshare", name = "text")
    public JAXBElement<String> createText(String value) {
        return new JAXBElement<String>(_Text_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sinai.ujaen.es/nlptoolsshare", name = "document")
    public JAXBElement<DocumentType> createDocument(DocumentType value) {
        return new JAXBElement<DocumentType>(_Document_QNAME, DocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NlptoolsshareType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sinai.ujaen.es/nlptoolsshare", name = "nlptoolsshare")
    public JAXBElement<NlptoolsshareType> createNlptoolsshare(NlptoolsshareType value) {
        return new JAXBElement<NlptoolsshareType>(_Nlptoolsshare_QNAME, NlptoolsshareType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TokensType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sinai.ujaen.es/nlptoolsshare", name = "tokens")
    public JAXBElement<TokensType> createTokens(TokensType value) {
        return new JAXBElement<TokensType>(_Tokens_QNAME, TokensType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SentenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sinai.ujaen.es/nlptoolsshare", name = "sentence")
    public JAXBElement<SentenceType> createSentence(SentenceType value) {
        return new JAXBElement<SentenceType>(_Sentence_QNAME, SentenceType.class, null, value);
    }

}
